# Generated by Django 3.1.7 on 2021-04-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0002_auto_20210407_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postID',
            field=models.CharField(max_length=40),
        ),
    ]
